# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringauthenticationtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 19, 29, 47, 59909), verbose_name='Expires'),
        ),
    ]
