"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3yu4i^j!he_-b05!$vl!lbkmlis2ian@ow^0srq44$irx$f8uz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'backend.apps.ems',
    'backend.apps.crm',
    'backend.apps.lms',
    'backend.apps.hashtags',
    # 'oauth2_provider',
    'social.apps.django_app.default',
    # 'rest_framework_social_oauth2',
    # 'rest_framework.authtoken',
    # 'django_facebook',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                # 'django_facebook.context_processors.facebook',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'backend.apps.crm.authentication.ExpiringTokenAuthenticationSystem'
        # 'rest_framework.authentication.TokenAuthentication',
        # 'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        # 'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':
        (
            # 'oauth2_provider.ext.rest_framework.TokenHasScope',
            'rest_framework.permissions.IsAuthenticated'
        )
}

AUTHENTICATION_BACKENDS = (
   # Facebook OAuth2

    'social.backends.facebook.FacebookAppOAuth2',
    'social.backends.facebook.FacebookOAuth2',

    # django-rest-framework-social-oauth2
    # 'rest_framework_social_oauth2.backends.DjangoOAuth2',

    # Django
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_FACEBOOK_KEY = '193207894363008'
# SOCIAL_AUTH_FACEBOOK_KEY = '161932934157171'
SOCIAL_AUTH_FACEBOOK_SECRET = '660848dc9ca623c9b80e356bd2081d1f'
# SOCIAL_AUTH_FACEBOOK_SECRET = 'c9941915e243207ab0bbcd08cec58bee'

# facebook testing
TEST_FACEBOOK_USER = 'rzjivmw_seligsteinsen_1467380851@tfbnw.net'
TEST_FACEBOOK_PASSWORD = 'testuser'

FACEBOOK_APP_ID = '193207894363008'
FACEBOOK_APP_SECRET = '660848dc9ca623c9b80e356bd2081d1f'



SOCIAL_AUTH_URL_NAMESPACE = 'social'
# SOCIAL_AUTH_USER_MODEL = 'apps.crm.models.Account'


SOCIAL_AUTH_USER_MODEL = 'crm.Account'
AUTH_USER_MODEL = 'crm.Account'

# Define SOCIAL_AUTH_FACEBOOK_SCOPE to get extra permissions from facebook. Email is not sent by default, to get it, you must request the email permission:
#SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'about', 'birthday', 'friends', 'likes', 'events',]
SOCIAL_AUTH_FACEBOOK_SCOPE = ['public_profile', 'email', 'user_about_me', 'user_birthday', 'user_events',]


PROPRIETARY_BACKEND_NAME = ('Facebook',)

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },

    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'JoinMeDB',
        'USER': 'JoinMeRoot',
        'PASSWORD': 'getconnected',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# ------------------------------------
# CORS HEADERS
# ------------------------------------
USE_ETAGS = False
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False
CORS_URLS_REGEX = r'^/api/.*$'


# AUTH_USER_MODEL = 'backend.apps.crm.models.Account'
# AUTH_USER_MODEL = 'crm.Account'

# ------------------------------------
# OAUTH2 SETTINGS
# ------------------------------------


# OAUTH2_PROVIDER = {
#     # this is the list of available scopes
#     'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'}
# }

#############################
#   FACEBOOK INFORMATION    #
#############################

FACEBOOK_API_VERSION = '2.6'